# Generated by Django 4.1.7 on 2023-03-27 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price_for_tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('price_for_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_for_ticket', to='blog.seanses', verbose_name='Стоимость билета')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector', to='blog.sector_salon', verbose_name='Сектор')),
            ],
            options={
                'verbose_name': 'Стоимость билета',
                'verbose_name_plural': 'Стоимость билетов',
                'ordering': ['price_for_ticket'],
            },
        ),
    ]
