# Generated by Django 4.1.7 on 2023-03-27 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moving_tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('operation', models.CharField(max_length=50, verbose_name='Операции')),
                ('employee', models.IntegerField(verbose_name='Сотрудник')),
                ('number_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_ticket', to='blog.tickets', verbose_name='Билет номер')),
            ],
            options={
                'verbose_name': 'Движение билета',
                'verbose_name_plural': 'Движение билетов',
                'ordering': ['number_ticket'],
            },
        ),
    ]
