# Generated by Django 4.1.7 on 2023-03-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='employees',
            name='title',
            field=models.IntegerField(verbose_name='Информация'),
        ),
    ]
