# Generated by Django 4.1.7 on 2023-03-27 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_job_title_alter_employees_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='blog.job_title', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='moving_tickets',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.employees', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='moving_tickets',
            name='number_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='blog.tickets', verbose_name='Билет номер'),
        ),
    ]
