# Generated by Django 4.1.7 on 2023-03-29 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_employees_title_alter_moving_tickets_employee_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job_title',
            new_name='JobTitle',
        ),
        migrations.AlterField(
            model_name='moving_tickets',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='blog.employees', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='moving_tickets',
            name='number_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_ticket', to='blog.tickets', verbose_name='Билет номер'),
        ),
    ]
