# Generated by Django 3.2 on 2023-04-04 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_cinema_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seanses',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_seanses', to='blog.cinema', verbose_name='Фильм'),
        ),
    ]
