# Generated by Django 3.2 on 2023-04-11 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0015_alter_seanses_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='moving_tickets',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='auth.user', verbose_name='Продавец'),
            preserve_default=False,
        ),
    ]
